# Generated by Django 3.1 on 2020-09-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
